language: node_js
node_js:
  - "8"
before_script:
  - npm install -g gulp-cli
before_deploy: gulp build:production && gulp --cwd docs build:production && ls dist
branches:
  only:
    - master
    - development
cache: npm
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
notifications:
  email: false
