language: node_js
node_js:
  - "node"
  - "6"

before_script:
  - npm install -g gulp-cli
script: cd docs
before_deploy: gulp build:production
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  email: polishedsapphire@gmail.com
  name: Joseph White
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
